In [1]:
# numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [3]:
#Craeting arrays

In [5]:
Sample_array =np.array([1,2,3,4])

In [7]:
Sample_array

array([1, 2, 3, 4])

In [10]:
Sam2_arr=np.array([1,2,3,4,5,6,7,8])

In [12]:
Sam2_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# 2D array (Matrix) with 2 rows and 2 columns

In [16]:
Sam_arr=np.array([[1,2],[3,4]])

In [17]:
Sam_arr

array([[1, 2],
       [3, 4]])

In [20]:
s_arr=np.array([[0,2],[1,4]])

In [21]:
s_arr

array([[0, 2],
       [1, 4]])

In [22]:
# 3d Tenser (2 matrices, each with 2 rows and 2 columns)

In [30]:
Sam_Tenser=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [31]:
Sam_Tenser

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

 Dimension

In [34]:
# 0-D Array --> Scalar
# eg--> 5

#1-D Array --> Vector
#eg--> [1,2,3,4,]

# 2-D array --> Matrix (rows and columns)
#eg--> [1,2]
 #     [5,6]

# 3-D array --> Tenser (page,rows ,column)

Properties of Array

In [36]:
Ex_arr=np.array([[1,2,3],[4,5,6]])

In [37]:
Ex_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#Shape

In [39]:
Ex_arr.shape

(2, 3)

In [40]:
#dimensions

In [41]:
Ex_arr.ndim

2

In [42]:
#totle elements

In [43]:
Ex_arr.size

6

In [44]:
#data type

In [45]:
Ex_arr.dtype

dtype('int64')

In [46]:
#special arrays

In [49]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.arange(0,10,2)
#start
#stop
#step

array([0, 2, 4, 6, 8])

In [56]:
np.arange(0,30,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [57]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [59]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [60]:
#indexing and slicing

In [61]:
sam_arr=np.array([1,2,3,4])

In [62]:
sam_arr

array([1, 2, 3, 4])

In [65]:
sam_arr[0]

np.int64(1)

In [67]:
sam_arr[1]

np.int64(2)

In [68]:
sam_arr[-1]

np.int64(4)

In [69]:
#slicing

In [71]:
Sample_array[1:3]

array([2, 3])

In [72]:
#Array operations

In [73]:
a=np.array([1,2,3])

In [74]:
b=np.array([4,5,6])

In [75]:
a

array([1, 2, 3])

In [76]:
b

array([4, 5, 6])

In [77]:
a+b

array([5, 7, 9])

In [78]:
a-b

array([-3, -3, -3])

In [79]:
a%b

array([1, 2, 3])

In [80]:
a*b

array([ 4, 10, 18])

In [81]:
#Mathematical Functions

In [82]:
Saple_array=np.array([1,4,9])

In [83]:
Saple_array

array([1, 4, 9])

In [84]:
np.sqrt(Saple_array)

array([1., 2., 3.])

In [86]:
np.exp(Saple_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [87]:
# Statistical function

In [88]:
Sample_array=np.array([1,2,3,4,5])

In [90]:
Sample_array

array([1, 2, 3, 4, 5])

In [92]:
np.median(Sample_array)

np.float64(3.0)

np.std(Sample_array)

In [94]:
np.std(Sample_array)

np.float64(1.4142135623730951)

In [95]:
np.min(Sample_array)

np.int64(1)

In [96]:
np.max(Sample_array)

np.int64(5)

In [97]:
np.mean(Sample_array)

np.float64(3.0)

In [98]:
#Array reshaping

In [111]:
sample_array=np.arange(6)

In [112]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [113]:
reshaped=sample_array.reshape(2,3)

In [114]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [115]:
#flattening

In [118]:
Sample_array=np.array([[1,2],[3,4]])

In [119]:
Sample_array

array([[1, 2],
       [3, 4]])

In [120]:
Sample_array.flatten()

array([1, 2, 3, 4])

In [121]:
Dis=np.array([[5,6],[3,5]])

In [122]:
Dis

array([[5, 6],
       [3, 5]])

In [123]:
Dis.flatten()

array([5, 6, 3, 5])

In [124]:
Sa_tenser=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [125]:
Sa_tenser.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
#joining Arrays

In [127]:
a=np.array([1,2])

In [128]:
b=np.array([3,4,])

In [129]:
a

array([1, 2])

In [130]:
b

array([3, 4])

In [131]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [132]:
# splitting Arrays

In [133]:
Sample_array=np.array([1,2,3,4])

In [135]:
Sample_array

array([1, 2, 3, 4])

In [137]:
np.array_split(Sample_array,2)

[array([1, 2]), array([3, 4])]

In [138]:
#Random Module


In [139]:
np.random.rand()

0.023757719790457488

In [140]:
np.random.randint(1,10,5)

array([3, 7, 6, 5, 7], dtype=int32)

In [141]:
#Axis Concept

In [142]:
Sample_array=np.array([[1,2],[3,4]])

In [143]:
Sample_array

array([[1, 2],
       [3, 4]])

In [144]:
np.sum(Sample_array, axis=0)

array([4, 6])

In [145]:
np.sum(Sample_array, axis=1)

array([3, 7])

In [146]:
#NaN and Missig Values

In [147]:
Sample_array=np.array([1,np.nan,3])

In [148]:
Sample_array

array([ 1., nan,  3.])

In [150]:
np.isnan(Sample_array)

array([False,  True, False])

In [151]:
#create two numpy arrays and perform element wise addition substraction, multiplication and modulas operations 

In [152]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])


In [153]:
a

array([10, 20, 30, 40])

In [154]:
b

array([1, 2, 3, 4])

In [155]:
a+b

array([11, 22, 33, 44])

In [156]:
a-b

array([ 9, 18, 27, 36])

In [157]:
a*b

array([ 10,  40,  90, 160])

In [158]:
a%b

array([0, 0, 0, 0])