weekly Assignment 
=======            
assignment no.4

SECTION A -- Exception handling

1. write a function safe_divide(a,b) that divides two umbers and handles ZeroDivisionError and TypeError separately, printing an appropriate message for each. use a finally block to print 'opertaional attempted' regardless of the outcome. test it with valid numbers, division by zero, and a string input.

In [2]:
def safe_division(a,b):
    try:
        result=a/b
        print("result is",result)
    except ZeroDivisionError:
        print("Error: cannot divide by zero ")
    except TypeError:
        print("Invaid input type")
    finally:
        print("Operation attempted")

In [4]:
# valid numbers
safe_division(6,3)

result is 2.0
Operation attempted


In [5]:
#division by zero
safe_division(10,0)

Error: cannot divide by zero 
Operation attempted


In [6]:
#type error
safe_division(10,'2')

Invaid input type
Operation attempted


2. write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a calling block and print a user-friendly message. Test it with at least 3 different values.

In [13]:
class InvalidAgeError(Exception):
    pass
def validate_age(age):
    if age<0:
        raise InvalidAgeError("Age cannot be negative")
    elif age>120:
        raise InvalidAgeError("Age cannot be greater than 120")
    else:
        print("valid age",age)
test_age=[-25,18,150,25]
for age in test_age:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print(f"Invalid age entered({age}),{e}")
        

Invalid age entered(-25),Age cannot be negative
valid age 18
Invalid age entered(150),Age cannot be greater than 120
valid age 25


3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list, e.g. user_inputs=['10','abc','0','5']) to enter a number and divide 100 by it. Handle the following in a single try block using multiple except clauses:
a. valueError if the input is not a number.
b. ZeroDivsionError if the input is zero.
c. A generic Exception as a catch-all for anything else.
 print the result if successful, otherwise print which error occurred.

In [15]:
user_input=['10','abc','0','5','25','100']
for i in user_input:
    try:
        num=int(i)
        result=100/num
        print(f"100/{num}={result}")
    except ValueError:
        print(f"ValueError: '{i}' is not valid number")
    except ZeroDivisionError:
        print("ZeroDivisionError:Cannot ddivide by zero")
    except Exception as e:
        print(f"an unexpected erroe occured: {e}")

100/10=10.0
ValueError: 'abc' is not valid number
ZeroDivisionError:Cannot ddivide by zero
100/5=20.0
100/25=4.0
100/100=1.0


Section B-- NumPy

4.Create a 1D Numpy array of integer from 1 to 20. perform the following:
a. Reshape it into 4x5 2D array.
b. Print the sum of each row and each column.
c. Extract all elements greater than 10 using bollean indexing.
d.Replace all even numbers in the array with -1

In [17]:
import numpy as np

arr=np.arange(1,21)
print("original array",arr)
arr_2d=arr.reshape(4,5)
print("\n 4x5 2D array",arr_2d)
row_sum=np.sum(arr_2d,axis=1)
col_sum=np.sum(arr_2d,axis=0)
print("\nSum of each row:")
print(row_sum)
print("\nSum of each column:")
print(col_sum)
greater_than_10=arr[arr>10]
print("\nElements greater than 10:")
print(greater_than_10)
modified_arr=arr.copy()
modified_arr[modified_arr%2==0]=-1
print("\nArray after replacing even numbers with -1:")
print(modified_arr)


original array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 4x5 2D array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of each row:
[15 40 65 90]

Sum of each column:
[34 38 42 46 50]

Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20]

Array after replacing even numbers with -1:
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


5.Create two NumPy rrays A and B as showm below and perform:
A=np.array([[1,2],[3,4]]) B=np.array(([5,6],[7,8]))
a. Element-wish addition, substraition, and multiplication
b.Matrix multiplaction using np.dot() or the @ operator
c.Transpose od A
d. The determinant and inverse of A using np.linalg

In [18]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)
print("\nElement-wise Addition (A + B):")
print(A + B)

print("\nElement-wise Subtraction (A - B):")
print(A - B)

print("\nElement-wise Multiplication (A * B):")
print(A * B)
print("\nMatrix Multiplication using np.dot():")
print(np.dot(A, B))
print("\nMatrix Multiplication using @ operator:")
print(A @ B)

print("\nTranspose of A:")
print(A.T)


det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print("\nDeterminant of A:")
print(det_A)

print("\nInverse of A:")
print(inv_A)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise Addition (A + B):
[[ 6  8]
 [10 12]]

Element-wise Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication (A * B):
[[ 5 12]
 [21 32]]

Matrix Multiplication using np.dot():
[[19 22]
 [43 50]]

Matrix Multiplication using @ operator:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


6.Generate a NumPy array of 15 random integers between 1 to 100 using np.randoom.randint() (set a seed of 42 for reproducibility ) than:
a. find the mean,median,standard deviation,min,max 
b. sort the array in descending order 
c. find the indices of the 3 largest values using np.argsort()
d.Normalize the array so all values lie between 0 and 1 

In [1]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 101, 15)

print("Original Array:",arr)
print("\nStatistics:")
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Standard Deviation =", np.std(arr))
print("Minimum =", np.min(arr))
print("Maximum =", np.max(arr))
desc_arr = np.sort(arr)[::-1]

print("\nArray sorted in descending order:")
print(desc_arr)

largest_indices = np.argsort(arr)[-3:][::-1]

print("\nIndices of the 3 largest values:")
print(largest_indices)

print("The 3 largest values are:")
print(arr[largest_indices])
normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("\nNormalized Array:")
print(normalized_arr)

Original Array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Statistics:
Mean = 58.06666666666667
Median = 72.0
Standard Deviation = 31.4843170836247
Minimum = 3
Maximum = 100

Array sorted in descending order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of the 3 largest values:
[11  1 10]
The 3 largest values are:
[100  93  88]

Normalized Array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


7.create a Pandas DataFrame from the dictionary below and perform the following:
data={"Name":["Aarav","priya","Karan","Meera","Sahil"],"Age":[23,21,25,22,24],"Department":["AI","Data Science","AI","Web Dev","Data Science"],"Score":[88,92,79,95,67],}
a.Display the frist 3 rows and the data types of each column.
b. Add a new column Grade based on Score(>=90'A',>=75'B',else'c')
c.sort the DataFrame by score in descending order
d.filter rows where Deparatment is 'AI'


In [2]:
import pandas as pd
data = {
    "Name": ["Aarav", "priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}
df = pd.DataFrame(data)
print("First 3 rows:")
print(df.head(3))

print("\nData types:")
print(df.dtypes)
def get_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 75:
        return 'B'
    else:
        return 'C'

df["Grade"] = df["Score"].apply(get_grade)

print("\nDataFrame with Grade:")
print(df)
df_sorted = df.sort_values(by="Score", ascending=False)

print("\nSorted by Score (descending):")
print(df_sorted)
df_ai = df[df["Department"] == "AI"]

print("\nDepartment = AI:")
print(df_ai)

First 3 rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  priya   21  Data Science     92
2  Karan   25            AI     79

Data types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (descending):
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Department = AI:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


8. Using trhe same DAtaFRame from Q7:
a. Group by Department and find the average score for each 
b. Find the row with the highest score using idxmax()
c.Rename the column score to marks
d.Drop the age column and display the resulting Dataframe.                                                                                       

In [4]:
import pandas as pd

data = {
    "Name": ["Aarav", "priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)
dept_avg = df.groupby("Department")["Score"].mean()
print(dept_avg)
max_index = df["Score"].idxmax()
highest_row = df.loc[max_index]
print(highest_row)
df_renamed = df.rename(columns={"Score": "Marks"})
print(df_renamed)
df_dropped = df.drop(columns=["Age"])
print(df_dropped)

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67
    Name    Department  Score
0  Aarav            AI     88
1  priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


9. Create a DataFrame with some missing values as shown below and handle thm:
import numpy as np data={"product":["pen","Notebook","Eraser","sharpner","Ruler"],"Price":[10,np.nan,5,8,np.nan],"Stock":[100,50,np.nan,30,20]}
a. check the number of missing values in each column using isnull().sum()
b.Fill missing price values with the column mean
c Drop rows where stock is still missing
d.Save the cleaned DataFRame to a CSV file named Cleaned_products.csv without the index

In [5]:
import numpy as np
import pandas as pd

data = {
    "product": ["pen", "Notebook", "Eraser", "sharpner", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)
print("Missing values in each column:")
print(df.isnull().sum())
df["Price"] = df["Price"].fillna(df["Price"].mean())
df = df.dropna(subset=["Stock"])
df.to_csv("Cleaned_products.csv", index=False)
print("\nCleaned DataFrame:")
print(df)

Missing values in each column:
product    0
Price      2
Stock      1
dtype: int64

Cleaned DataFrame:
    product      Price  Stock
0       pen  10.000000  100.0
1  Notebook   7.666667   50.0
3  sharpner   8.000000   30.0
4     Ruler   7.666667   20.0


10. Read the csv file created in Q9 (cleaned_product.csv) back into a new dataframe and:
a. print its shape and column names
b.add a nwe column Total_Values as price multiplied by stock
c.Use describe() to print summaray statistics of the numeric columns
d.Wrap the file reading step in a try_except block to handel the case where the file does not exist(FileNotFoundError)

In [6]:
import pandas as pd
try: 
    df = pd.read_csv("Cleaned_products.csv")
    print("Shape of DataFrame:", df.shape)
    print("Column names:", df.columns.tolist())
   
    df["Total_Values"] = df["Price"] * df["Stock"]
    print("\nSummary Statistics:")
    print(df.describe())
    print("\nUpdated DataFrame:")
    print(df)

except FileNotFoundError:
    print("Error: The file 'Cleaned_products.csv' does not exist.")

Shape of DataFrame: (4, 3)
Column names: ['product', 'Price', 'Stock']

Summary Statistics:
           Price       Stock  Total_Values
count   4.000000    4.000000      4.000000
mean    8.333333   50.000000    444.166667
std     1.122167   35.590261    382.500303
min     7.666667   20.000000    153.333333
25%     7.666667   27.500000    218.333333
50%     7.833333   40.000000    311.666667
75%     8.500000   62.500000    537.500000
max    10.000000  100.000000   1000.000000

Updated DataFrame:
    product      Price  Stock  Total_Values
0       pen  10.000000  100.0   1000.000000
1  Notebook   7.666667   50.0    383.333333
2  sharpner   8.000000   30.0    240.000000
3     Ruler   7.666667   20.0    153.333333
